"""DIMER inference package for the pinned ``google/pix2struct-ai2d-base`` checkpoint."""

from .pipeline import (
    DECODING,
    DEFAULT_MAX_NEW_TOKENS,
    DEFAULT_WEIGHTS_DIR,
    INPUT_SCHEMA,
    MAX_IMAGE_SIDE,
    MAX_NEW_TOKENS,
    MAX_OPTION_CHARS,
    MAX_OPTIONS,
    MAX_PATCHES,
    MAX_QUESTION_CHARS,
    MIN_IMAGE_SIDE,
    MIN_OPTIONS,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    Pix2StructAI2DPipeline,
    evaluation_report,
    format_prompt,
    header_font_bytes,
    match_option,
    normalize_answer,
    stage_missing_files,
    validate_inputs,
    verify_snapshot,
)

__all__ = [
    "DECODING",
    "DEFAULT_MAX_NEW_TOKENS",
    "DEFAULT_WEIGHTS_DIR",
    "INPUT_SCHEMA",
    "MAX_IMAGE_SIDE",
    "MAX_NEW_TOKENS",
    "MAX_OPTIONS",
    "MAX_OPTION_CHARS",
    "MAX_PATCHES",
    "MAX_QUESTION_CHARS",
    "MIN_IMAGE_SIDE",
    "MIN_OPTIONS",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "Pix2StructAI2DPipeline",
    "evaluation_report",
    "format_prompt",
    "header_font_bytes",
    "match_option",
    "normalize_answer",
    "stage_missing_files",
    "validate_inputs",
    "verify_snapshot",
]
